FROM portainer/agent:alpine as original_agent

FROM cr.portainer.io/portainer/dev-toolkit:2021.11

# Install system requirements
RUN apt install -y --no-install-recommends \
    less \
    augeas-tools \
    rsync \
    iproute2 \
    psmisc \
    tmux \
    grunt \
    netcat \
    sshpass \
    iputils-ping && \
    apt autoremove -y && \
    apt clean

RUN apt install -y --no-install-recommends \
    openssh-server && \
    apt autoremove -y && \
    apt clean

ENV GOPATH=/go

# copy some binary files such as `docker` from original agent image
COPY --from=original_agent /app /app
COPY --from=original_agent /app/kubectl /usr/bin/
RUN rm /app/agent

# copy fancy bashrc 
COPY /bashrc /fancy_bashrc

# install dlv
RUN /usr/local/go/bin/go install github.com/go-delve/delve/cmd/dlv@latest

# install kind
RUN curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64 && \
    install kind /usr/local/bin/ && \
    rm kind

# COPY scripts /scripts

COPY entry.sh /entry.sh
COPY init_portainer_workspace.sh /init_portainer_workspace.sh
COPY start_portainer_workspace.sh /start_portainer_workspace.sh
ENTRYPOINT ["/entry.sh"]
#CMD ["/usr/sbin/sshd", "-D", "-e", "-f", "/etc/ssh/sshd_config"]
