#!/usr/bin/env sh

set -x

docker stop portainer-devkit
docker rm portainer-devkit

docker run -d --rm \
--name portainer-devkit \
--network portainer-devkit \
-e DEVKIT_DEBUG=true \
--ip 192.168.100.10 \
-p 3000:3000 \
-v "/home/simon/workspace:/home/workspace" \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /var/lib/docker/volumes:/var/lib/docker/volumes \
mcpacino/portainer-devkit-workspace:dev

sleep 3
docker exec -it portainer-devkit bash
