FROM portainer/agent:alpine as original_agent

FROM ubuntu:20.04

# Install system requirements
RUN apt update && apt install -y --no-install-recommends \
    less \
    augeas-tools \
    rsync \
    openssh-server

RUN apt install -y --no-install-recommends \
    tmux \
    psmisc \
    iproute2 \
    iputils-ping && \
    apt autoremove -y && \
    apt clean

# copy some binary files such as `docker` from original agent image
COPY --from=original_agent /app /app

EXPOSE 22

COPY entry.sh /entry.sh
ENTRYPOINT ["/entry.sh"]

CMD ["/usr/sbin/sshd", "-D", "-e", "-f", "/etc/ssh/sshd_config"]
