#!/usr/bin/env bash

if [[ "$1" == "latest" ]]; then
  docker image tag mcpacino/portainer-devkit-workspace:dev mcpacino/portainer-devkit-workspace:latest
  docker image push mcpacino/portainer-devkit-workspace
else
  docker image push mcpacino/portainer-devkit-workspace:dev
fi
