#!/usr/bin/env sh

set -x

exec_in() { docker exec $@; }

# create network for dind and minikube
docker network create --driver=bridge --subnet=192.168.50.0/24 --gateway=192.168.50.1 agent-ssh


# spin up a dind container named s01
docker run --privileged -d --rm --hostname s01 --name s01 --network agent-ssh --ip 192.168.50.4 docker:dind
sleep 3

# s01 init
exec_in s01 docker swarm init
#TOKEN_WORKER="$(exec_in s01 docker swarm join-token -q worker)"

# s02 join
#exec_in swarm02 docker swarm join --token $TOKEN_WORKER s01:2377


exec_in s01 \
  docker network create \
    --driver overlay \
    portainer_agent_network

exec_in s01 \
  docker service create \
    --name portainer_edge_agent \
    --network portainer_agent_network \
    --mode global \
    --mount type=bind,src=//var/run/docker.sock,dst=/var/run/docker.sock \
    --mount type=bind,src=//var/lib/docker/volumes,dst=/var/lib/docker/volumes \
    --mount type=bind,src=//,dst=/host \
    --mount type=volume,src=portainer_agent_data,dst=/data \
    --publish mode=host,target=22,published=22 \
    --publish mode=host,target=9001,published=9001 \
    --publish mode=host,target=80,published=80 \
    mcpacino/portainer-devkit-agent:latest

