FROM portainer/agent:alpine as original_agent

FROM ubuntu:22.04

# Install system requirements
RUN apt update && apt install -y --no-install-recommends \
    less \
    augeas-tools \
    rsync \
    psmisc \
    iproute2 \
    wget \
    openssh-server \
    iputils-ping \
    ca-certificates


RUN \
    apt autoremove -y && \
    apt clean


## Install Golang
#ARG TARGETOS=linux
#ARG TARGETARCH=arm64
#ARG GO_VERSION=go1.20.6.${TARGETOS}-${TARGETARCH}
#RUN cd /tmp \
#	&& wget -q https://dl.google.com/go/${GO_VERSION}.tar.gz \
#	&& tar -xf ${GO_VERSION}.tar.gz \
#	&& mv go /usr/local \
#    && rm ${GO_VERSION}.tar.gz
#
## Configuring Golang PATH
#ENV PATH "$PATH:/usr/local/go/bin:/root/go/bin"
#RUN echo 'PATH="$PATH:/usr/local/go/bin:/root/go/bin"' >> /etc/profile


# Generate HostKey /etc/ssh/ssh_host_*_key for sshd
# Doing so in dockerfile can keep the SSH fingerprint unchanged
RUN ssh-keygen -A

# copy some binary files such as `docker` from original agent image
COPY --from=original_agent /app /app

EXPOSE 22 9001

COPY agent/entry /entry
ENTRYPOINT ["/entry/entry.sh"]
