FROM portainer/agent:alpine as original_agent

FROM ubuntu:22.04

# Install system requirements
RUN apt update && apt install -y --no-install-recommends \
    less \
    augeas-tools \
    rsync \
    psmisc \
    iproute2 \
    wget \
    openssh-server \
    iputils-ping \
    ca-certificates


RUN \
    apt autoremove -y && \
    apt clean

# Generate HostKey /etc/ssh/ssh_host_*_key for sshd
# Doing so in dockerfile can keep the SSH fingerprint unchanged
RUN ssh-keygen -A

# copy some binary files such as `docker` from original agent image
COPY --from=original_agent /app /app

EXPOSE 22 9001

COPY agent/entry /entry
ENTRYPOINT ["/entry/entry.sh"]
