#!/usr/bin/env bash

set -x

if [[ "$1" == "latest" ]]; then
  echo "push latest"
  docker image tag mcpacino/portainer-devkit-agent:dev mcpacino/portainer-devkit-agent
  docker image push mcpacino/portainer-devkit-agent
else
  echo "push dev"
  docker image push mcpacino/portainer-devkit-agent:dev
fi
