#!/usr/bin/env bash

# usage:
#
# push with tag latest
#   ./push latest
#
# push with tag dev
#   ./push

set -x

if [[ "$1" == "latest" ]]; then
  echo "push latest"
  docker image tag mcpacino/portainer-devkit-agent:dev mcpacino/portainer-devkit-agent
  docker image push mcpacino/portainer-devkit-agent
else
  echo "push dev"
  docker image push mcpacino/portainer-devkit-agent:dev
fi
