#!/usr/bin/env sh

set -x

# create network for dind and minikube
docker network create --driver=bridge --subnet=192.168.50.0/24 --gateway=192.168.50.1 agent-ssh

# spin up a dind container named d01
docker run --privileged -d --rm --hostname d01 --name d01 --network agent-ssh --ip 192.168.50.3 docker:dind
sleep 3

# spin up agent container in d01
docker exec d01 \
  docker run -d \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /var/lib/docker/volumes:/var/lib/docker/volumes \
    -v /:/host \
    -v portainer_agent_data:/data \
    --restart always \
    --hostname portainer_agent \
    --name portainer_agent \
    -e SSH_PASSWORD=root \
    --publish mode=host,target=22,published=22 \
    --publish mode=host,target=80,published=80 \
    --publish mode=host,target=9001,published=9001 \
    mcpacino/portainer-devkit-agent:latest


echo "ssh root@d01"

